name: tokens
description: "Tokens: Token Scanning"
version: 0.0.2
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  collection: ^1.16.0
  common_extensions:
    git:
      url: https://github.com/DevPackUP/CommonExtensions
      ref: dpdt
  vignette_charcode: any
  leuco_logbase: any
dependency_overrides:
  vignette_charcode:
    path: "D:\\Users\\haruka.dev\\ResDev\\_Codes\\Lang\\Dart\\.CoreLibraries\\Vignette_CharCode"
  leuco_logbase:
    path: "D:\\Users\\haruka.dev\\ResDev\\_Codes\\Lang\\Dart\\.CoreLibraries\\Leuco_LogBase"
# dev_dependencies:
#   lints: ^1.0.0
#   test: ^1.16.0
